accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from .forms import CustomLoginForm
from django.views.generic import TemplateView


app_name = "accounts"

urlpatterns = [

    url(r'^$', TemplateView.as_view(template_name='accounts/home.html'), name="home"),

    url(r"^register/$", views.RegisterView.as_view(), name='register'),
    url(r"^otp/resend/$", views.otp_resend, name='otp_resend'),

    url(r"^otp/verify/$", views.OTPVerifyView.as_view(), name='otp_verify'),

    url(r"^password/change/$", views.password_change, name='password_change'),

    url(r"^password/reset/$", views.PasswordResetView.as_view(), name='password_reset'),

    url(r"^password/reset/new/$", views.PasswordResetNewView.as_view(), name='password_reset_new'),
    url(r"^password/reset/otp/resend/$", views.password_reset_otp_resend, name='password_reset_otp_resend'),

    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html', authentication_form=CustomLoginForm),
        name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    #
    # url(r'^otp_input/$', views.otp_input, name='otp_input')

]

e_project_accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from __future__ import unicode_literals
import uuid
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager
from .validators import phone_number_validator
from django.conf import settings
import requests
from django.shortcuts import redirect
from django.contrib import messages
from . import alert_messages


api_key_2fa = settings.API_KEY_2FA


def send_otp_2fa(request, phone):
    if 'user_session_data' in request.session:
        del request.session['user_session_data']
    url = "http://2factor.in/API/V1/{api_key}/SMS/{phone}/AUTOGEN/OTPSEND".format(api_key=api_key_2fa, phone=phone)
    response = requests.request("GET", url)
    data = response.json()
    request.session['user_session_data'] = data['Details']
    return True


class User(AbstractBaseUser, PermissionsMixin):
    phone = models.CharField(_('phone number'), max_length=13, validators=[phone_number_validator, ], unique=True)
    email = models.EmailField(_('email address'), blank=True)

    phone_verified = models.BooleanField(default=False)
    first_name = models.CharField(_('first name'), max_length=32, blank=True)
    last_name = models.CharField(_('last name'), max_length=32, blank=True)
    city = models.CharField(_('city'), max_length=30, blank=True, default="Pune")
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=False)
    is_staff = models.BooleanField(_('staff'), default=False)
    is_superuser = models.BooleanField(_('superuser'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.phone

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = "{} {}".format(self.first_name, self.last_name)
        return full_name.strip()

    def get_first_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    @property
    def get_wallet(self):
        return self.wallet

    def make_phone_verified_and_active(self):
        self.is_active = True
        self.phone_verified = True
        self.save()

    def otp_generate(self, request):
        if hasattr(self, 'usersession'):
            self.usersession.delete()
        user_session = UserSession.objects.create(user=self)
        request.session["user_session_uuid"] = str(user_session.uuid)
        send_otp_2fa(request, self.phone)
        messages.info(request, alert_messages.REGISTERATION_OTP_SENT_MESSAGE)
        return redirect("accounts:otp_verify")

    def password_reset_otp_generate(self, request):
        if hasattr(self, 'usersession'):
            self.usersession.delete()
        user_session = UserSession.objects.create(user=self)
        request.session["user_session_uuid"] = str(user_session.uuid)
        send_otp_2fa(request, self.phone)
        messages.info(request, alert_messages.PASSWORD_RESET_OTP_SENT_MESSAGE)
        return redirect("accounts:password_reset_new")


class UserSession(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)

    def __str__(self):
        return "{} - {}".format(self.user.__str__,
                                     self.uuid)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from . models import User
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import password_validation
from django.conf import settings


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=14, widget=forms.TextInput(attrs={"class": "input-medium bfh-phone", "data-format": "+91dddddddddd"}))


class RegisterForm(UserCreationForm):
    phone = forms.CharField(max_length=14, widget=forms.TextInput(attrs={"class": "input-medium bfh-phone", "data-format": "+91dddddddddd"}))

    class Meta:
        model = User
        fields = ('phone', 'email', 'password1', 'password2',)


class PasswordResetForm(forms.Form):

    phone = forms.CharField(max_length=14, widget=forms.TextInput(attrs={"class": "input-medium bfh-phone", "data-format": "+91dddddddddd"}))

    class Meta:
        fields = ('phone', )


class PasswordResetNewForm(forms.Form):

    otp = forms.IntegerField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1==password2:
            return self.cleaned_data
        else:
            raise ValidationError("Both password must be same.")

    def _post_clean(self):
        super()._post_clean()
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password)
            except forms.ValidationError as error:
                self.add_error('password2', error)


    class Meta:
        fields = ('otp', 'password1', 'password2')


class OTPForm(forms.Form):
    otp = forms.IntegerField()

    class Meta:
        fields = ('otp', )

accounts/views.py
import requests
from .models import UserSession
from .forms import RegisterForm, PasswordResetForm, PasswordResetNewForm, OTPForm
from django.views.generic import TemplateView, ListView, FormView, View
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import alert_messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404

USER_MODEL = get_user_model()
api_key = settings.API_KEY_2FA


def check_otp_2fa(otp, otp_session_data):
    url = "http://2factor.in/API/V1/{0}/SMS/VERIFY/{1}/{2}".format(api_key,
                                                                   otp_session_data, otp)
    response = requests.request("GET", url)
    data = response.json()
    return data['Status'] == "Success"


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = "accounts/register.html"

    def form_valid(self, form):
        new_user = form.save()
        return new_user.otp_generate(self.request)


def otp_resend(request):
    try:
        user = UserSession.objects.get(uuid=request.session.get("user_session_uuid")).user
        return user.otp_generate(request)
    except UserSession.DoesNotExist:
        raise Http404("Bad Request")


def password_reset_otp_resend(request):
    try:
        user = UserSession.objects.get(uuid=request.session.get("user_session_uuid")).user
        return user.password_reset_otp_generate(request)
    except UserSession.DoesNotExist:
        raise Http404("Bad Request")


class OTPVerifyView(FormView):

    form_class = OTPForm
    template_name = "accounts/otp_verify.html"

    def post(self, request, *args, **kwargs):
        otp = request.POST['otp']
        user_session = UserSession.objects.get(uuid=request.session["user_session_uuid"])
        user = user_session.user
        otp_match = check_otp_2fa(otp=otp, otp_session_data=request.session['user_session_data'])
        if otp_match:
            user.make_phone_verified_and_active()
            del request.session['user_session_uuid']
            del request.session['user_session_data']
            user_session.delete()
            messages.success(request, alert_messages.REGISTERATION_SUCCESS_MESSAGE)
            login(request, user)
            return redirect("accounts:home")
        else:
            messages.warning(request, alert_messages.OTP_INCORRECT_MESSAGE)
            return redirect("accounts:otp_verify")


@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, alert_messages.PASSWORD_CHANGED_SUCCESS_MESSAGE)
            return redirect('accounts:home')
        else:
            messages.error(request, alert_messages.FORM_INVALID_MESSAGE)
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/password_change.html', {
        'form': form
    })


class PasswordResetView(FormView):

    template_name = "accounts/password_reset.html"
    form_class = PasswordResetForm

    def form_valid(self, form):
        phone = form.cleaned_data.get('phone')
        try:
            user = USER_MODEL.objects.get(phone=phone)
            if user.is_active:
                return user.password_reset_otp_generate(self.request)
            else:
                messages.warning(self, alert_messages.USER_NON_ACTIVE_MESSAGE)
        except USER_MODEL.DoesNotExist:
            messages.warning(self.request, alert_messages.PHONE_NOT_REGISTERED_MESSAGE)
            return redirect("accounts:password_reset")


class PasswordResetNewView(FormView):

    template_name = "accounts/password_reset_new.html"
    form_class = PasswordResetNewForm

    def form_valid(self, form):
        otp = form.cleaned_data.get('otp')
        password1 = form.cleaned_data.get('password1')
        password2 = form.cleaned_data.get('password2')
        user_session = UserSession.objects.get(uuid=self.request.session["user_session_uuid"])
        user = user_session.user

        otp_match = check_otp_2fa(otp=otp, otp_session_data=self.request.session['user_session_data'])
        if otp_match:
            user.set_password(password1)
            user.save()
            del self.request.session['user_session_uuid']
            del self.request.session['user_session_data']
            user_session.delete()
            messages.success(self.request, "Password changed")
            login(self.request, user)
            return redirect("accounts:home")
        else:
            messages.warning(self.request, "please enter correct OTP!")
            return redirect("accounts:password_reset_new")


# class PasswordChange(LoginRequiredMixin, FormView):
#     form_class = PasswordChangeForm
#     template_name = "accounts/password_change.html"
#
#     def form_valid(self, form):
#         user = form.save()
#         update_session_auth_hash(self.request, user)  # Important!
#         messages.success(self.request, alert_messages.PASSWORD_CHANGED_SUCCESS_MESSAGE)
#         return redirect('accounts:home')


# def otp_verify(request):
#     if request.method == "POST":
#         user_otp = request.POST['otp']
#         url = "http://2factor.in/API/V1/{0}/SMS/VERIFY/{1}/{2}".format(api_key, request.session['user_session_data'], user_otp)
#         response = requests.request("GET", url)
#         data = response.json()
#         user_session = UserSession.objects.get(uuid=request.session["user_session_uuid"])
#         user = user_session.user
#         if data['Status'] == "Success":
#             user.is_active = True
#             user.phone_verified = True
#             user.save()
#             del request.session['user_session_uuid']
#             del request.session['user_session_data']
#             user_session.delete()
#             messages.success(request, alert_messages.REGISTERATION_SUCCESS_MESSAGE)
#             login(request, user)
#             return redirect("accounts:home")
#         else:
#             messages.warning(request, alert_messages.OTP_INCORRECT_MESSAGE)
#             return render(request, "accounts/otp_verify.html")
#     else:
#         return render(request, "accounts/otp_verify.html")

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    {% block full_title %}<title>{% block title %}Base{% endblock %} | Eway Print</title>{% endblock %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-formhelpers/2.3.0/css/bootstrap-formhelpers.css">


</head>
<body>
{% if messages %}
    {% for meesage in messages %}
        <span class="alert  alert-{{ meesage.tags }}">{{ meesage }}</span>
    {% endfor %}
{% endif %}
    <div class="container jumbotron text-center">

        {% block body %}

        {% endblock %}

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-formhelpers/2.3.0/js/bootstrap-formhelpers.min.js"></script>

</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
    <h2>Welcome To Eway Print</h2>

    <br><br><br>

        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}"><button class="btn btn-danger">Logout</button></a>

            <a href="{% url 'accounts:password_change' %}"><button class="btn btn-info">Change Password</button></a>
        {% else %}
            <a href="{% url 'accounts:login' %}"><button class="btn btn-info">Login</button></a>


        {% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block body %}

    <h2>Log in | Eway Print</h2>

    <div class="container col-lg-4">
        <form method="post">
            {% csrf_token %}


            {{ form|crispy }}


            <input class="btn btn-info" value="Login" type="submit"/>
        </form>

        <p>Create new account ! <a href="{% url 'accounts:register' %}">Register</a></p>
        <a href="{% url 'accounts:password_reset' %}" class="text-danger">Forgot Password?</a>

    </div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block title %}Logged Out{% endblock %}

{% block body %}
    <h4>You have succesfully logged out..</h4><br>
    <h5>Thanks for your precious time with us.</h5>
{% endblock %}

accounts/templates/accounts/otp_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

	{% if messgaes %}
		{% for message in messages %}
			<span class="alert alert-{{ message.tags }}" style="color: {{ message.tags }}">
				{{ message }}
			</span>
		{% endfor %}
	{% endif %}


    <form method="post" action="{% url "accounts:otp_input" %}">
        <h3>Register</h3>

        {% csrf_token %}

        <br>
        <input name="otp" placeholder="enter otp">

        <hr>
        <input value="Submit OTP" type="submit">

    </form>

</body>
</html>

accounts/templates/accounts/otp_verify.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}OTP Verify{% endblock %}

{% block body %}


    <div class="container col-lg-4">

        <form method="POST">
            {{form.non_field_errors}}
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Verify</button>
        </form>

    <a href="{% url "accounts:otp_resend" %}">Resend OTP</a>

    </div>

{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Change Password{% endblock %}

{% block body %}

    <h2>Change Password | Eway Print</h2>

    <div class="container col-lg-4">

        <form method="POST">
            {{form.non_field_errors}}
            {% csrf_token %}
            {% for field in form %}
                {{field.label_tag}}
                    {{ field }}
                {{ field.help_text | safe }}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            <button type="submit">Change Password</button>
        </form>

    </div>

{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block body %}

    <h2>Register | Eway Print</h2>

    <div class="container col-lg-4">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Change Password">
        </form>

        <p>Already have an account? <a href="{% url "accounts:login" %}">Login!</a></p>

    </div>

{% endblock %}

accounts/templates/accounts/password_reset_new.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Set Password{% endblock %}

{% block body %}

    <h2>Set New Password | Eway Print</h2>

    <div class="container col-lg-4">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Change Password">
        </form>

        <a href="{% url "accounts:password_reset_otp_resend" %}">Resend OTP</a>
        <br><br>

        <p>Already have an account? <a href="{% url "accounts:login" %}">Login!</a></p>

    </div>

{% endblock %}

accounts/templates/accounts/register.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>


    <form method="post">
        <h3>Register</h3>

        {% csrf_token %}
        <hr>
        {{ form|crispy }}
        <hr>
        <input value="Register" type="submit">

    </form>

</body>
</html>